// flow-typed signature: 28af05e98878239fb7686f8c42ed507e
// flow-typed version: <<STUB>>/@types/react-dom_v^18.0.11/flow_v0.208.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react-dom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react-dom' {
  declare module.exports: any;
}
