// flow-typed signature: 974403d8c5be4f6f5e83961ca389fd63
// flow-typed version: <<STUB>>/vite_v^4.3.9/flow_v0.208.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vite/bin/vite' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-8124a809' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-93197d47' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-c423598f' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-e8f070e8' {
  declare module.exports: any;
}

declare module 'vite/dist/node/chunks/dep-f0c7dae0' {
  declare module.exports: any;
}

declare module 'vite/dist/node/cli' {
  declare module.exports: any;
}

declare module 'vite/dist/node/constants' {
  declare module.exports: any;
}

declare module 'vite/dist/node' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vite/bin/vite.js' {
  declare module.exports: $Exports<'vite/bin/vite'>;
}
declare module 'vite/dist/node/chunks/dep-8124a809.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-8124a809'>;
}
declare module 'vite/dist/node/chunks/dep-93197d47.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-93197d47'>;
}
declare module 'vite/dist/node/chunks/dep-c423598f.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-c423598f'>;
}
declare module 'vite/dist/node/chunks/dep-e8f070e8.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-e8f070e8'>;
}
declare module 'vite/dist/node/chunks/dep-f0c7dae0.js' {
  declare module.exports: $Exports<'vite/dist/node/chunks/dep-f0c7dae0'>;
}
declare module 'vite/dist/node/cli.js' {
  declare module.exports: $Exports<'vite/dist/node/cli'>;
}
declare module 'vite/dist/node/constants.js' {
  declare module.exports: $Exports<'vite/dist/node/constants'>;
}
declare module 'vite/dist/node/index' {
  declare module.exports: $Exports<'vite/dist/node'>;
}
declare module 'vite/dist/node/index.js' {
  declare module.exports: $Exports<'vite/dist/node'>;
}
