const MOVE_RECENTLY_UPDATED: string[] = [
  "basecover",
  "blockattack",
  "burnout",
  "charm",
  "crowd",
  "defheal",
  "flykick",
  "hazeball",
  "heartpass",
  "hum",
  "kick",
  "markattack",
  "nightshade",
  "overheat",
  "passionstrike",
  "protectcheer",
  "rush",
  "sad",
  "speech",
  "squeeze",
  "stretch",
  "substitute",
];

export default MOVE_RECENTLY_UPDATED;
